In [2]:
import tensorflow as tf
import logging
from autologging import logged, traced, TRACE
logging.basicConfig(level=logging.INFO, format="%(name)s.%(funcName)s\t%(message)s")
logging.info(f"tensorflow version {tf.version.VERSION}")

root.<module>	tensorflow version 2.4.0


In [3]:
import numpy as np
from zebrastack_model_v2 import prepare_images

from tensorflow import keras
(train_images, _), (test_images, _) = keras.datasets.fashion_mnist.load_data()
train_images, test_images = train_images[:len(train_images)//1], test_images[:len(test_images)//1]
logging.info(f"train_images: {train_images.shape} {train_images.dtype}")

train_images = prepare_images(train_images)
test_images = prepare_images(test_images)

root.<module>	train_images: (60000, 28, 28) uint8


In [4]:
from zebrastack_model_v2 import ZebraStackModel

model = ZebraStackModel(latent_dim=8)
model.encoder.summary()

retina = model.encoder.input
dense_shape = model.encoder.get_layer('ait_local').output_shape
output = model.encoder.get_layer('z_mean_log_var')
logging.info(f"{retina} {dense_shape} {output}")

model.decoder.summary()

root.<module>	KerasTensor(type_spec=TensorSpec(shape=(None, 64, 64, 1), dtype=tf.float32, name='retina_64'), name='retina_64', description="created by layer 'retina_64'") (None, 6, 6, 2) <tensorflow.python.keras.layers.core.Dense object at 0x00000204326869A0>
Model: "v1_to_pulvinar_encoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
v1_conv2d (Conv2D)           (None, 64, 64, 16)        416       
_________________________________________________________________
v1_maxpool (MaxPooling2D)    (None, 32, 32, 16)        0         
_________________________________________________________________
v1_dropout (SpatialDropout2D (None, 32, 32, 16)        0         
_________________________________________________________________
v2_conv2d (Conv2D)           (None, 32, 32, 16)        2320      
_________________________________________________________________
v2_maxpool (MaxPooling2D)    (None, 16, 16, 16) 

In [5]:
import matplotlib.pyplot as plt
from zebrastack_model_v2 import NotebookCallback

fig, ax = plt.subplots(2,10,figsize=(15,3))
nb_callback = NotebookCallback(fig)

model.train(train_images, test_images, nb_callback)

root.train	logs\fit\20210318-155611
root.forall_batch	0: (16, 64, 64, 1)


ValueError: Layer v1_to_pulvinar_encoder expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor: shape=(), dtype=int32, numpy=0>, <tf.Tensor: shape=(16, 64, 64, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       ...,


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]]], dtype=float32)>]

In [ ]:
import matplotlib.pyplot as plt
test_latent = model.encoder(test_images[0:10,...])

def sigmoid(x):
    return np.exp(-np.logaddexp(0, -x))

re_test_images = model.decoder(test_latent[...,0:8])
re_test_images = sigmoid(re_test_images)

quantiles = [0.05, 0.95]

fig, ax = plt.subplots(2,10,figsize=(15,3))
for n in range(10):
    q_test = np.quantile(test_images[n],quantiles)
    ax[0][n].imshow(test_images[n], cmap='gray', vmin=q_test[0], vmax=q_test[1])

    reshape_test_image = np.reshape(re_test_images[n], (64,64))
    q_re = np.quantile(reshape_test_image,quantiles)
    ax[1][n].imshow(reshape_test_image, cmap='gray', vmin=q_re[0], vmax=q_re[1])